### ISSUE TITLE
__block typeof(self) this = self - shouldn't that be __weak under ARC?

### ISSUE THREAD

**Issue by benvium** [Wolox/WLXBluetoothDevice#17]
In a few places throughout the code it looks like you've tried to avoid retain cycles using:

```
__block typeof(self) this = self;
```

.. and then using 'this' rather than self inside the block. 

I believe  the __block modifier will cause self to be retained under ARC. Apple changed the behaviour of __block when ARC was introduced, and __weak may be a better solution here.

E.g.

```
__weak typeof(self) this = self;
```

Two examples are at WLXBluetoothConnectionManager.m line 202, and 264. Of course the behaviour may be different as the 'this' reference may be nilled inside the block.

Here's a reference:
http://stackoverflow.com/questions/4352561/retain-cycle-on-self-with-blocks

**Comment by guidomb** [comment]
@benvium you are right after reading a little bit I am going to use __weak outside and __strong inside the block. I don't want to use [libextobjc](https://github.com/jspahrsummers/libextobjc) because I don't want to include external dependecies (The only one I am using is CocoalumberJack). Thanks for letting me know about this issue

**Comment by benvium** [comment]
Good stuff. Sounds sensible to use __weak. 

libextobjc looks unnecessary to me for this purpose. Interesting library though, didn't know that one.
